<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class MayaSliderSettings {
	private $maya_slider_settings_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'maya_slider_settings_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'maya_slider_settings_page_init' ) );
	}

	public function maya_slider_settings_add_plugin_page() {
		add_menu_page(
			'Maya Slider Settings', // page_title
			'Maya Slider Settings', // menu_title
			'manage_options', // capability
			'maya-slider-settings', // menu_slug
			array( $this, 'maya_slider_settings_create_admin_page' ), // function
			'dashicons-admin-settings', // icon_url
			81 // position
		);
	}

	public function maya_slider_settings_create_admin_page() {
		$this->maya_slider_settings_options = get_option( 'maya_slider_settings' ); ?>

		<div class="wrap">
			<h2>Maya Slider Settings</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'maya_slider_settings_option_group' );
					do_settings_sections( 'maya-slider-settings-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function maya_slider_settings_page_init() {
		register_setting(
			'maya_slider_settings_option_group', // option_group
			'maya_slider_settings', // option_name
			array( $this, 'maya_slider_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'maya_slider_settings_setting_section', // id
			'Settings', // title
			array( $this, 'maya_slider_settings_section_info' ), // callback
			'maya-slider-settings-admin' // page
		);

		add_settings_field(
			'loop', // id
			'Loop', // title
			array( $this, 'loop_callback' ), // callback
			'maya-slider-settings-admin', // page
			'maya_slider_settings_setting_section' // section
		);

		add_settings_field(
			'mouse_drag', // id
			'Mouse Drag', // title
			array( $this, 'mouse_drag_callback' ), // callback
			'maya-slider-settings-admin', // page
			'maya_slider_settings_setting_section' // section
		);

		add_settings_field(
			'touch_drag', // id
			'Touch Drag', // title
			array( $this, 'touch_drag_callback' ), // callback
			'maya-slider-settings-admin', // page
			'maya_slider_settings_setting_section' // section
		);

		add_settings_field(
			'navigation', // id
			'Navigation', // title
			array( $this, 'navigation_callback' ), // callback
			'maya-slider-settings-admin', // page
			'maya_slider_settings_setting_section' // section
		);

		add_settings_field(
			'dots', // id
			'Dots', // title
			array( $this, 'dots_callback' ), // callback
			'maya-slider-settings-admin', // page
			'maya_slider_settings_setting_section' // section
		);

		add_settings_field(
			'autoplay', // id
			'Autoplay', // title
			array( $this, 'autoplay_callback' ), // callback
			'maya-slider-settings-admin', // page
			'maya_slider_settings_setting_section' // section
		);

		add_settings_field(
			'autoplay_timeout', // id
			'Autoplay Timeout', // title
			array( $this, 'autoplay_timeout_callback' ), // callback
			'maya-slider-settings-admin', // page
			'maya_slider_settings_setting_section' // section
		);

		add_settings_field(
			'autoplay_hover_pause', // id
			'Autoplay Hover Pause', // title
			array( $this, 'autoplay_hover_pause_callback' ), // callback
			'maya-slider-settings-admin', // page
			'maya_slider_settings_setting_section' // section
		);
	}

	public function maya_slider_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['loop'] ) ) {
			$sanitary_values['loop'] = $input['loop'];
		}

		if ( isset( $input['mouse_drag'] ) ) {
			$sanitary_values['mouse_drag'] = $input['mouse_drag'];
		}

		if ( isset( $input['touch_drag'] ) ) {
			$sanitary_values['touch_drag'] = $input['touch_drag'];
		}

		if ( isset( $input['navigation'] ) ) {
			$sanitary_values['navigation'] = $input['navigation'];
		}

		if ( isset( $input['dots'] ) ) {
			$sanitary_values['dots'] = $input['dots'];
		}

		if ( isset( $input['autoplay'] ) ) {
			$sanitary_values['autoplay'] = $input['autoplay'];
		}

		if ( isset( $input['autoplay_timeout'] ) ) {
			$sanitary_values['autoplay_timeout'] = sanitize_text_field( $input['autoplay_timeout'] );
		}

		if ( isset( $input['autoplay_hover_pause'] ) ) {
			$sanitary_values['autoplay_hover_pause'] = $input['autoplay_hover_pause'];
		}

		return $sanitary_values;
	}

	public function maya_slider_settings_section_info() {
		
	}

	public function loop_callback() {
		printf(
			'<input type="checkbox" name="maya_slider_settings[loop]" id="loop" value="true" %s> <label for="loop">Infinity loop. Duplicate last and first items to get loop illusion. Default: false</label>',
			( isset( $this->maya_slider_settings_options['loop'] ) && $this->maya_slider_settings_options['loop'] === 'true' ) ? 'checked' : ''
		);
	}

	public function mouse_drag_callback() {
		printf(
			'<input type="checkbox" name="maya_slider_settings[mouse_drag]" id="mouse_drag" value="true" %s> <label for="mouse_drag">Mouse drag enabled. Default: true</label>',
			( isset( $this->maya_slider_settings_options['mouse_drag'] ) && $this->maya_slider_settings_options['mouse_drag'] === 'true' ) ? 'checked' : ''
		);
	}

	public function touch_drag_callback() {
		printf(
			'<input type="checkbox" name="maya_slider_settings[touch_drag]" id="touch_drag" value="true" %s> <label for="touch_drag">Touch drag enabled. Default: true</label>',
			( isset( $this->maya_slider_settings_options['touch_drag'] ) && $this->maya_slider_settings_options['touch_drag'] === 'true' ) ? 'checked' : ''
		);
	}

	public function navigation_callback() {
		printf(
			'<input type="checkbox" name="maya_slider_settings[navigation]" id="navigation" value="true" %s> <label for="navigation">Show next/prev buttons. Default: false</label>',
			( isset( $this->maya_slider_settings_options['navigation'] ) && $this->maya_slider_settings_options['navigation'] === 'true' ) ? 'checked' : ''
		);
	}

	public function dots_callback() {
		printf(
			'<input type="checkbox" name="maya_slider_settings[dots]" id="dots" value="true" %s> <label for="dots">Show dots navigation. Default: true</label>',
			( isset( $this->maya_slider_settings_options['dots'] ) && $this->maya_slider_settings_options['dots'] === 'true' ) ? 'checked' : ''
		);
	}

	public function autoplay_callback() {
		printf(
			'<input type="checkbox" name="maya_slider_settings[autoplay]" id="autoplay" value="true" %s> <label for="autoplay">Autoplay. Default: false</label>',
			( isset( $this->maya_slider_settings_options['autoplay'] ) && $this->maya_slider_settings_options['autoplay'] === 'true' ) ? 'checked' : ''
		);
	}

	public function autoplay_timeout_callback() {
		printf(
			'<input class="regular-text" type="text" name="maya_slider_settings[autoplay_timeout]" id="autoplay_timeout" value="%s">',
			isset( $this->maya_slider_settings_options['autoplay_timeout'] ) ? esc_attr( $this->maya_slider_settings_options['autoplay_timeout']) : '5000'
		);
	}

	public function autoplay_hover_pause_callback() {
		printf(
			'<input type="checkbox" name="maya_slider_settings[autoplay_hover_pause]" id="autoplay_hover_pause" value="true" %s> <label for="autoplay_hover_pause">Pause on mouse hover. Default: false</label>',
			( isset( $this->maya_slider_settings_options['autoplay_hover_pause'] ) && $this->maya_slider_settings_options['autoplay_hover_pause'] === 'true' ) ? 'checked' : ''
		);
	}

}
if ( is_admin() )
	$maya_slider_settings = new MayaSliderSettings();

/* 
 * Retrieve this value with:
 * $maya_slider_settings_options = get_option( 'maya_slider_settings' ); // Array of All Options
 * $loop = $maya_slider_settings_options['loop']; // Loop
 * $mouse_drag = $maya_slider_settings_options['mouse_drag']; // Mouse Drag
 * $touch_drag = $maya_slider_settings_options['touch_drag']; // Touch Drag
 * $navigation = $maya_slider_settings_options['navigation']; // Navigation
 * $dots = $maya_slider_settings_options['dots']; // Dots
 * $autoplay = $maya_slider_settings_options['autoplay']; // Autoplay
 * $autoplay_timeout = $maya_slider_settings_options['autoplay_timeout']; // Autoplay Timeout
 * $autoplay_hover_pause = $maya_slider_settings_options['autoplay_hover_pause']; // Autoplay Hover Pause
 */